import os

def add_rosetta_header(file_path):
    header_lines = [
        "HEADER    THEORETICAL MODEL                         07-NOV-23   XXXX",
        "EXPDTA    THEORETICAL MODEL",
        "REMARK 220",
        "REMARK 220 EXPERIMENTAL DETAILS",
        "REMARK 220  EXPERIMENT TYPE                : THEORETICAL MODELLING",
        f"REMARK 220  DATE OF DATA COLLECTION        : 07-NOV-23",
        "REMARK 220",
        "REMARK 220 REMARK: MODEL GENERATED BY ROSETTA",
        "REMARK 220  VERSION 2023.06+release.27ba97a",
    ]

    with open(file_path, 'r') as original_file:
        original_content = original_file.read()

    with open(file_path, 'w') as modified_file:
        modified_file.write('\n'.join(header_lines) + '\n' + original_content)

def add_header_to_folder(input_folder, output_folder):
    for filename in os.listdir(input_folder):
        if filename.endswith(".pdb"):
            input_file_path = os.path.join(input_folder, filename)
            output_file_path = os.path.join(output_folder, filename)
            add_rosetta_header(input_file_path)
            os.rename(input_file_path, output_file_path)

if __name__ == "__main__":
    input_folder = "/u/jawall/pymol/af_MYD88_1WH4_IRAK4DD/merged_iso_relaxed_af"
    output_folder = "/u/jawall/pymol/af_MYD88_1WH4_IRAK4DD/head_merge_iso_relaxed_af"

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    add_header_to_folder(input_folder, output_folder)
